import React, { VFC, ReactNode } from 'react'
import Head from 'next/head'
import { Header } from '../molecules/Header'

interface Props {
  children: ReactNode
}

export const Layout: VFC<Props> = ({ children }) => {
  return(
    <>
      <Head>
        <title>Numa.blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {children}
      </main>
      <footer>

      </footer>
    </>
  )
}